package com.hnq.study.dao.mapper;

import com.hnq.study.dao.domain.CsdnOverview;
import com.hnq.study.dao.domain.CsdnOverviewCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CsdnOverviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int countByExample(CsdnOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int deleteByExample(CsdnOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int insert(CsdnOverview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int insertSelective(CsdnOverview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    List<CsdnOverview> selectByExampleWithBLOBsWithRowbounds(CsdnOverviewCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    List<CsdnOverview> selectByExampleWithBLOBs(CsdnOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    List<CsdnOverview> selectByExampleWithRowbounds(CsdnOverviewCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    List<CsdnOverview> selectByExample(CsdnOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    CsdnOverview selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CsdnOverview record, @Param("example") CsdnOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CsdnOverview record, @Param("example") CsdnOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CsdnOverview record, @Param("example") CsdnOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CsdnOverview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CsdnOverview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_csdn_extract_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CsdnOverview record);
}