package com.hnq.study.dao.mapper;

import com.hnq.study.dao.domain.ZhiHuOverview;
import com.hnq.study.dao.domain.ZhiHuOverviewCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ZhiHuOverviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int countByExample(ZhiHuOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int deleteByExample(ZhiHuOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int insert(ZhiHuOverview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int insertSelective(ZhiHuOverview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    List<ZhiHuOverview> selectByExampleWithBLOBsWithRowbounds(ZhiHuOverviewCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    List<ZhiHuOverview> selectByExampleWithBLOBs(ZhiHuOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    List<ZhiHuOverview> selectByExampleWithRowbounds(ZhiHuOverviewCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    List<ZhiHuOverview> selectByExample(ZhiHuOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    ZhiHuOverview selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ZhiHuOverview record, @Param("example") ZhiHuOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") ZhiHuOverview record, @Param("example") ZhiHuOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ZhiHuOverview record, @Param("example") ZhiHuOverviewCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ZhiHuOverview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(ZhiHuOverview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ZhiHuOverview record);
}