package com.hnq.study.dao.domain;

import java.io.Serializable;
import java.util.Date;

public class TouTiaoMissingGoods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toutiao_missing_goods.id
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toutiao_missing_goods.account_id
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toutiao_missing_goods.product_id
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toutiao_missing_goods.goods_url
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    private String goodsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toutiao_missing_goods.status
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toutiao_missing_goods.create_time
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column toutiao_missing_goods.last_update_time
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table toutiao_missing_goods
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toutiao_missing_goods.id
     *
     * @return the value of toutiao_missing_goods.id
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toutiao_missing_goods.id
     *
     * @param id the value for toutiao_missing_goods.id
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toutiao_missing_goods.account_id
     *
     * @return the value of toutiao_missing_goods.account_id
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toutiao_missing_goods.account_id
     *
     * @param accountId the value for toutiao_missing_goods.account_id
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toutiao_missing_goods.product_id
     *
     * @return the value of toutiao_missing_goods.product_id
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toutiao_missing_goods.product_id
     *
     * @param productId the value for toutiao_missing_goods.product_id
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toutiao_missing_goods.goods_url
     *
     * @return the value of toutiao_missing_goods.goods_url
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public String getGoodsUrl() {
        return goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toutiao_missing_goods.goods_url
     *
     * @param goodsUrl the value for toutiao_missing_goods.goods_url
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public void setGoodsUrl(String goodsUrl) {
        this.goodsUrl = goodsUrl == null ? null : goodsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toutiao_missing_goods.status
     *
     * @return the value of toutiao_missing_goods.status
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toutiao_missing_goods.status
     *
     * @param status the value for toutiao_missing_goods.status
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toutiao_missing_goods.create_time
     *
     * @return the value of toutiao_missing_goods.create_time
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toutiao_missing_goods.create_time
     *
     * @param createTime the value for toutiao_missing_goods.create_time
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column toutiao_missing_goods.last_update_time
     *
     * @return the value of toutiao_missing_goods.last_update_time
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column toutiao_missing_goods.last_update_time
     *
     * @param lastUpdateTime the value for toutiao_missing_goods.last_update_time
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toutiao_missing_goods
     *
     * @mbggenerated Mon Aug 19 14:28:46 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", accountId=").append(accountId);
        sb.append(", productId=").append(productId);
        sb.append(", goodsUrl=").append(goodsUrl);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}