package com.hnq.study.dao.domain;

import java.io.Serializable;
import java.util.Date;

public class ZhiHuOverview implements Serializable {
    /**
     * 自增主键
     */
    private Long id;

    /**
     * 此次爬取任务id
     */
    private Long taskId;

    /**
     * 爬取关键字
     */
    private String keyword;

    /**
     * 爬取的问题
     */
    private String question;

    /**
     * 回答这个问题的作者的昵称
     */
    private String author;

    /**
     * 作者观点的被赞同数
     */
    private Integer agree;

    /**
     * 作者观点的被评论数
     */
    private Integer comments;

    /**
     * 作者观点链接
     */
    private String link;

    /**
     * 发布时间
     */
    private Date publicTime;

    /**
     * 编辑时间
     */
    private Date editTime;

    /**
     * 创建时间
     */
    private Date createDate;

    /**
     * 修改时间
     */
    private Date lastUpdateDate;

    /**
     * 作者对问题的观点
     */
    private String overview;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.id
     *
     * @return the value of t_zhihu_extract_result.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.id
     *
     * @param id the value for t_zhihu_extract_result.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.task_id
     *
     * @return the value of t_zhihu_extract_result.task_id
     *
     * @mbggenerated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.task_id
     *
     * @param taskId the value for t_zhihu_extract_result.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.keyword
     *
     * @return the value of t_zhihu_extract_result.keyword
     *
     * @mbggenerated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.keyword
     *
     * @param keyword the value for t_zhihu_extract_result.keyword
     *
     * @mbggenerated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.question
     *
     * @return the value of t_zhihu_extract_result.question
     *
     * @mbggenerated
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.question
     *
     * @param question the value for t_zhihu_extract_result.question
     *
     * @mbggenerated
     */
    public void setQuestion(String question) {
        this.question = question == null ? null : question.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.author
     *
     * @return the value of t_zhihu_extract_result.author
     *
     * @mbggenerated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.author
     *
     * @param author the value for t_zhihu_extract_result.author
     *
     * @mbggenerated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.agree
     *
     * @return the value of t_zhihu_extract_result.agree
     *
     * @mbggenerated
     */
    public Integer getagree() {
        return agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.agree
     *
     * @param agree the value for t_zhihu_extract_result.agree
     *
     * @mbggenerated
     */
    public void setagree(Integer agree) {
        this.agree = agree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.comments
     *
     * @return the value of t_zhihu_extract_result.comments
     *
     * @mbggenerated
     */
    public Integer getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.comments
     *
     * @param comments the value for t_zhihu_extract_result.comments
     *
     * @mbggenerated
     */
    public void setComments(Integer comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.link
     *
     * @return the value of t_zhihu_extract_result.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.link
     *
     * @param link the value for t_zhihu_extract_result.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.public_time
     *
     * @return the value of t_zhihu_extract_result.public_time
     *
     * @mbggenerated
     */
    public Date getPublicTime() {
        return publicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.public_time
     *
     * @param publicTime the value for t_zhihu_extract_result.public_time
     *
     * @mbggenerated
     */
    public void setPublicTime(Date publicTime) {
        this.publicTime = publicTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.edit_time
     *
     * @return the value of t_zhihu_extract_result.edit_time
     *
     * @mbggenerated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.edit_time
     *
     * @param editTime the value for t_zhihu_extract_result.edit_time
     *
     * @mbggenerated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.create_date
     *
     * @return the value of t_zhihu_extract_result.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.create_date
     *
     * @param createDate the value for t_zhihu_extract_result.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.last_update_date
     *
     * @return the value of t_zhihu_extract_result.last_update_date
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.last_update_date
     *
     * @param lastUpdateDate the value for t_zhihu_extract_result.last_update_date
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_zhihu_extract_result.overview
     *
     * @return the value of t_zhihu_extract_result.overview
     *
     * @mbggenerated
     */
    public String getOverview() {
        return overview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_zhihu_extract_result.overview
     *
     * @param overview the value for t_zhihu_extract_result.overview
     *
     * @mbggenerated
     */
    public void setOverview(String overview) {
        this.overview = overview == null ? null : overview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhihu_extract_result
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskId=").append(taskId);
        sb.append(", keyword=").append(keyword);
        sb.append(", question=").append(question);
        sb.append(", author=").append(author);
        sb.append(", agree=").append(agree);
        sb.append(", comments=").append(comments);
        sb.append(", link=").append(link);
        sb.append(", publicTime=").append(publicTime);
        sb.append(", editTime=").append(editTime);
        sb.append(", createDate=").append(createDate);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", overview=").append(overview);
        sb.append("]");
        return sb.toString();
    }
}