package com.hnq.study.dao.domain;

import java.io.Serializable;
import java.util.Date;

public class BaiduHot implements Serializable {
    private Integer id;

    private String titleLine1;

    private Integer titleLine2;

    private String titleLine3;

    private String titleLine4;

    private String hotStockName1;

    private String hotStockCode1;

    private Double hotStockPrice1;

    private String hotStockIncrement1;

    private String hotStockName2;

    private String hotStockCode2;

    private Double hotStockPrice2;

    private String hotStockIncrement2;

    private String hotStockName3;

    private String hotStockCode3;

    private Double hotStockPrice3;

    private String hotStockIncrement3;

    /**
     * 创建时间
     */
    private Date createDate;

    /**
     * 最后更新时间
     */
    private Date lastUpdateDate;

    private String drivingThing;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table baidu_hot
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.id
     *
     * @return the value of baidu_hot.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.id
     *
     * @param id the value for baidu_hot.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.title_line1
     *
     * @return the value of baidu_hot.title_line1
     *
     * @mbggenerated
     */
    public String getTitleLine1() {
        return titleLine1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.title_line1
     *
     * @param titleLine1 the value for baidu_hot.title_line1
     *
     * @mbggenerated
     */
    public void setTitleLine1(String titleLine1) {
        this.titleLine1 = titleLine1 == null ? null : titleLine1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.title_line2
     *
     * @return the value of baidu_hot.title_line2
     *
     * @mbggenerated
     */
    public Integer getTitleLine2() {
        return titleLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.title_line2
     *
     * @param titleLine2 the value for baidu_hot.title_line2
     *
     * @mbggenerated
     */
    public void setTitleLine2(Integer titleLine2) {
        this.titleLine2 = titleLine2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.title_line3
     *
     * @return the value of baidu_hot.title_line3
     *
     * @mbggenerated
     */
    public String getTitleLine3() {
        return titleLine3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.title_line3
     *
     * @param titleLine3 the value for baidu_hot.title_line3
     *
     * @mbggenerated
     */
    public void setTitleLine3(String titleLine3) {
        this.titleLine3 = titleLine3 == null ? null : titleLine3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.title_line4
     *
     * @return the value of baidu_hot.title_line4
     *
     * @mbggenerated
     */
    public String getTitleLine4() {
        return titleLine4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.title_line4
     *
     * @param titleLine4 the value for baidu_hot.title_line4
     *
     * @mbggenerated
     */
    public void setTitleLine4(String titleLine4) {
        this.titleLine4 = titleLine4 == null ? null : titleLine4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_name_1
     *
     * @return the value of baidu_hot.hot_stock_name_1
     *
     * @mbggenerated
     */
    public String getHotStockName1() {
        return hotStockName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_name_1
     *
     * @param hotStockName1 the value for baidu_hot.hot_stock_name_1
     *
     * @mbggenerated
     */
    public void setHotStockName1(String hotStockName1) {
        this.hotStockName1 = hotStockName1 == null ? null : hotStockName1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_code_1
     *
     * @return the value of baidu_hot.hot_stock_code_1
     *
     * @mbggenerated
     */
    public String getHotStockCode1() {
        return hotStockCode1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_code_1
     *
     * @param hotStockCode1 the value for baidu_hot.hot_stock_code_1
     *
     * @mbggenerated
     */
    public void setHotStockCode1(String hotStockCode1) {
        this.hotStockCode1 = hotStockCode1 == null ? null : hotStockCode1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_price_1
     *
     * @return the value of baidu_hot.hot_stock_price_1
     *
     * @mbggenerated
     */
    public Double getHotStockPrice1() {
        return hotStockPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_price_1
     *
     * @param hotStockPrice1 the value for baidu_hot.hot_stock_price_1
     *
     * @mbggenerated
     */
    public void setHotStockPrice1(Double hotStockPrice1) {
        this.hotStockPrice1 = hotStockPrice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_increment_1
     *
     * @return the value of baidu_hot.hot_stock_increment_1
     *
     * @mbggenerated
     */
    public String getHotStockIncrement1() {
        return hotStockIncrement1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_increment_1
     *
     * @param hotStockIncrement1 the value for baidu_hot.hot_stock_increment_1
     *
     * @mbggenerated
     */
    public void setHotStockIncrement1(String hotStockIncrement1) {
        this.hotStockIncrement1 = hotStockIncrement1 == null ? null : hotStockIncrement1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_name_2
     *
     * @return the value of baidu_hot.hot_stock_name_2
     *
     * @mbggenerated
     */
    public String getHotStockName2() {
        return hotStockName2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_name_2
     *
     * @param hotStockName2 the value for baidu_hot.hot_stock_name_2
     *
     * @mbggenerated
     */
    public void setHotStockName2(String hotStockName2) {
        this.hotStockName2 = hotStockName2 == null ? null : hotStockName2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_code_2
     *
     * @return the value of baidu_hot.hot_stock_code_2
     *
     * @mbggenerated
     */
    public String getHotStockCode2() {
        return hotStockCode2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_code_2
     *
     * @param hotStockCode2 the value for baidu_hot.hot_stock_code_2
     *
     * @mbggenerated
     */
    public void setHotStockCode2(String hotStockCode2) {
        this.hotStockCode2 = hotStockCode2 == null ? null : hotStockCode2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_price_2
     *
     * @return the value of baidu_hot.hot_stock_price_2
     *
     * @mbggenerated
     */
    public Double getHotStockPrice2() {
        return hotStockPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_price_2
     *
     * @param hotStockPrice2 the value for baidu_hot.hot_stock_price_2
     *
     * @mbggenerated
     */
    public void setHotStockPrice2(Double hotStockPrice2) {
        this.hotStockPrice2 = hotStockPrice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_increment_2
     *
     * @return the value of baidu_hot.hot_stock_increment_2
     *
     * @mbggenerated
     */
    public String getHotStockIncrement2() {
        return hotStockIncrement2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_increment_2
     *
     * @param hotStockIncrement2 the value for baidu_hot.hot_stock_increment_2
     *
     * @mbggenerated
     */
    public void setHotStockIncrement2(String hotStockIncrement2) {
        this.hotStockIncrement2 = hotStockIncrement2 == null ? null : hotStockIncrement2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_name_3
     *
     * @return the value of baidu_hot.hot_stock_name_3
     *
     * @mbggenerated
     */
    public String getHotStockName3() {
        return hotStockName3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_name_3
     *
     * @param hotStockName3 the value for baidu_hot.hot_stock_name_3
     *
     * @mbggenerated
     */
    public void setHotStockName3(String hotStockName3) {
        this.hotStockName3 = hotStockName3 == null ? null : hotStockName3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_code_3
     *
     * @return the value of baidu_hot.hot_stock_code_3
     *
     * @mbggenerated
     */
    public String getHotStockCode3() {
        return hotStockCode3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_code_3
     *
     * @param hotStockCode3 the value for baidu_hot.hot_stock_code_3
     *
     * @mbggenerated
     */
    public void setHotStockCode3(String hotStockCode3) {
        this.hotStockCode3 = hotStockCode3 == null ? null : hotStockCode3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_price_3
     *
     * @return the value of baidu_hot.hot_stock_price_3
     *
     * @mbggenerated
     */
    public Double getHotStockPrice3() {
        return hotStockPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_price_3
     *
     * @param hotStockPrice3 the value for baidu_hot.hot_stock_price_3
     *
     * @mbggenerated
     */
    public void setHotStockPrice3(Double hotStockPrice3) {
        this.hotStockPrice3 = hotStockPrice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.hot_stock_increment_3
     *
     * @return the value of baidu_hot.hot_stock_increment_3
     *
     * @mbggenerated
     */
    public String getHotStockIncrement3() {
        return hotStockIncrement3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.hot_stock_increment_3
     *
     * @param hotStockIncrement3 the value for baidu_hot.hot_stock_increment_3
     *
     * @mbggenerated
     */
    public void setHotStockIncrement3(String hotStockIncrement3) {
        this.hotStockIncrement3 = hotStockIncrement3 == null ? null : hotStockIncrement3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.create_date
     *
     * @return the value of baidu_hot.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.create_date
     *
     * @param createDate the value for baidu_hot.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.last_update_date
     *
     * @return the value of baidu_hot.last_update_date
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.last_update_date
     *
     * @param lastUpdateDate the value for baidu_hot.last_update_date
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column baidu_hot.driving_thing
     *
     * @return the value of baidu_hot.driving_thing
     *
     * @mbggenerated
     */
    public String getDrivingThing() {
        return drivingThing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column baidu_hot.driving_thing
     *
     * @param drivingThing the value for baidu_hot.driving_thing
     *
     * @mbggenerated
     */
    public void setDrivingThing(String drivingThing) {
        this.drivingThing = drivingThing == null ? null : drivingThing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table baidu_hot
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", titleLine1=").append(titleLine1);
        sb.append(", titleLine2=").append(titleLine2);
        sb.append(", titleLine3=").append(titleLine3);
        sb.append(", titleLine4=").append(titleLine4);
        sb.append(", hotStockName1=").append(hotStockName1);
        sb.append(", hotStockCode1=").append(hotStockCode1);
        sb.append(", hotStockPrice1=").append(hotStockPrice1);
        sb.append(", hotStockIncrement1=").append(hotStockIncrement1);
        sb.append(", hotStockName2=").append(hotStockName2);
        sb.append(", hotStockCode2=").append(hotStockCode2);
        sb.append(", hotStockPrice2=").append(hotStockPrice2);
        sb.append(", hotStockIncrement2=").append(hotStockIncrement2);
        sb.append(", hotStockName3=").append(hotStockName3);
        sb.append(", hotStockCode3=").append(hotStockCode3);
        sb.append(", hotStockPrice3=").append(hotStockPrice3);
        sb.append(", hotStockIncrement3=").append(hotStockIncrement3);
        sb.append(", createDate=").append(createDate);
        sb.append(", lastUpdateDate=").append(lastUpdateDate);
        sb.append(", drivingThing=").append(drivingThing);
        sb.append("]");
        return sb.toString();
    }
}